[package]
name = "tosdr-cli"
version = "0.1.0"
edition = "2021"

[dependencies.clap]
version = "4.4.7"
features = ["derive"]

[dependencies.serde]
version = "1.0.190"
features = ["derive"]

[dependencies.ureq]
version = "2.8.0"
features = ["json"]
